export const ROUTES = {
  HOME: '/',
  PROPERTIES: '/properties',
  PROPERTY_DETAIL: '/properties/:slug',
  AREAS: '/areas',
  AREA_DETAIL: '/areas/:slug',
  ABOUT: '/about',
  CONTACT: '/contact',
  GOLDEN_VISA: '/golden-visa',
  BUYER_GUIDES: '/buyer-guides',
  BUYER_GUIDE_DETAIL: '/buyer-guides/:slug',
  INSIGHTS: '/insights',
  BLOG: '/blog',
  BLOG_POST: '/blog/:slug',
  PRIVACY: '/privacy',
  TERMS: '/terms',

  // Admin Routes
  ADMIN_LOGIN: '/admin/login',
  ADMIN_DASHBOARD: '/admin',
  ADMIN_PROPERTIES: '/admin/properties',
  ADMIN_PROPERTY_NEW: '/admin/properties/new',
  ADMIN_PROPERTY_EDIT: '/admin/properties/:id',
  ADMIN_AREAS: '/admin/areas',
  ADMIN_AREA_NEW: '/admin/areas/new',
  ADMIN_AREA_EDIT: '/admin/areas/:id',
  ADMIN_BLOG: '/admin/blog',
  ADMIN_BLOG_NEW: '/admin/blog/new',
  ADMIN_BLOG_EDIT: '/admin/blog/:id',
  ADMIN_BUYER_GUIDES: '/admin/buyer-guides',
  ADMIN_BUYER_GUIDE_NEW: '/admin/buyer-guides/new',
  ADMIN_BUYER_GUIDE_EDIT: '/admin/buyer-guides/:id',
  ADMIN_GOLDEN_VISA: '/admin/golden-visa',
  ADMIN_INSIGHTS: '/admin/insights',
  ADMIN_CONTACT: '/admin/contact',
  ADMIN_SETTINGS: '/admin/settings',
}
