import { createClient } from '@supabase/supabase-js'

const supabaseUrl = 'https://ycrlkkkoxrsmugidznri.supabase.co'
const supabaseKey = 'sb_publishable_H_b_GUihEZhLN3WYVfj-zg_HK2eyRLy'

const supabase = createClient(supabaseUrl, supabaseKey)

// Try to sign up a new temp user and use session directly
const tempEmail = `populate_${Date.now()}@emlakbanq.com`
const tempPassword = 'PopulateTemp123!'

async function populate() {
  console.log('Creating temp user for data population...')
  const { data: signUpData, error: signUpError } = await supabase.auth.signUp({
    email: tempEmail,
    password: tempPassword,
  })

  if (signUpError) {
    console.error('SignUp failed:', signUpError.message)
    console.log('\nTrying without auth (RLS might allow inserts)...')
  } else {
    console.log('Session obtained:', signUpData.session ? 'Yes' : 'No (email confirmation needed)')
    if (signUpData.session) {
      console.log('Using authenticated session')
    }
  }

  // Try operations regardless - RLS might allow them or session might be active

  // ── 0. DELETE OLD DATA ──────────────────────────────────────────
  console.log('\n── Deleting old data ──')
  const tables = ['properties', 'areas', 'blog_posts', 'market_highlights', 'top_areas_roi', 'golden_visa_content']
  for (const table of tables) {
    // Use gte on created_at to match all rows
    const { error, count } = await supabase.from(table).delete().gte('created_at', '1970-01-01')
    if (error) console.error(`  ✗ ${table}: ${error.message}`)
    else console.log(`  ✓ ${table} cleared`)
  }

  // ── 1. TOP AREAS ROI (most critical - this is what user wants fixed) ──
  console.log('\n── Inserting top areas ROI (Alanya) ──')
  const topAreasRoi = [
    { area: {"tr": "Cikcilli", "en": "Cikcilli", "de": "Cikcilli", "ru": "Джикджилли", "bs": "Cikcilli"}, roi: '%9-14', price_range: '€80K - €280K', trend: 'up', sort_order: 0 },
    { area: {"tr": "Mahmutlar", "en": "Mahmutlar", "de": "Mahmutlar", "ru": "Махмутлар", "bs": "Mahmutlar"}, roi: '%8-12', price_range: '€65K - €180K', trend: 'up', sort_order: 1 },
    { area: {"tr": "Avsallar", "en": "Avsallar", "de": "Avsallar", "ru": "Авсаллар", "bs": "Avsallar"}, roi: '%8-12', price_range: '€70K - €350K', trend: 'up', sort_order: 2 },
    { area: {"tr": "Kestel", "en": "Kestel", "de": "Kestel", "ru": "Кестель", "bs": "Kestel"}, roi: '%7-11', price_range: '€100K - €650K', trend: 'up', sort_order: 3 },
    { area: {"tr": "Konaklı", "en": "Konakli", "de": "Konaklı", "ru": "Конаклы", "bs": "Konaklı"}, roi: '%7-11', price_range: '€75K - €200K', trend: 'stable', sort_order: 4 },
    { area: {"tr": "Tosmur", "en": "Tosmur", "de": "Tosmur", "ru": "Тосмур", "bs": "Tosmur"}, roi: '%7-10', price_range: '€90K - €300K', trend: 'stable', sort_order: 5 },
    { area: {"tr": "Oba", "en": "Oba", "de": "Oba", "ru": "Оба", "bs": "Oba"}, roi: '%6-10', price_range: '€120K - €450K', trend: 'up', sort_order: 6 },
    { area: {"tr": "Kargıcak", "en": "Kargicak", "de": "Kargıcak", "ru": "Каргыджак", "bs": "Kargıcak"}, roi: '%5-9', price_range: '€350K - €800K', trend: 'stable', sort_order: 7 }
  ]

  const { error: roiError } = await supabase.from('top_areas_roi').insert(topAreasRoi)
  if (roiError) console.error(`  ✗ top_areas_roi: ${roiError.message}`)
  else console.log(`  ✓ ${topAreasRoi.length} ROI entries inserted`)

  // ── 2. MARKET HIGHLIGHTS ────────────────────────────────────────
  console.log('\n── Inserting market highlights ──')
  const highlights = [
    { text: {"tr": "Alanya gayrimenkul piyasası 2024'te %18 değer artışı kaydetti", "en": "Alanya real estate market recorded 18% value appreciation in 2024", "de": "Alanyas Immobilienmarkt verzeichnete 2024 eine Wertsteigerung von 18%", "ru": "Рынок недвижимости Аланьи вырос на 18% в 2024 году", "bs": "Tržište nekretnina u Alanji zabilježilo je rast od 18% u 2024"}, sort_order: 0 },
    { text: {"tr": "Yabancı yatırımcı sayısı bir önceki yıla göre %25 arttı", "en": "Foreign investor numbers increased by 25% compared to previous year", "de": "Die Zahl ausländischer Investoren stieg um 25%", "ru": "Число иностранных инвесторов выросло на 25%", "bs": "Broj stranih investitora porastao je za 25%"}, sort_order: 1 },
    { text: {"tr": "Alanya'da ortalama kira getirisi %8-12 arasında seyrediyor", "en": "Average rental yield in Alanya ranges between 8-12%", "de": "Die durchschnittliche Mietrendite in Alanya liegt zwischen 8-12%", "ru": "Средняя арендная доходность в Аланье составляет 8-12%", "bs": "Prosječni prinos od najma u Alanji kreće se između 8-12%"}, sort_order: 2 },
    { text: {"tr": "2025'te 5.000+ yeni konut projesi teslim edildi", "en": "5,000+ new residential units delivered in 2025", "de": "Über 5.000 neue Wohneinheiten wurden 2025 übergeben", "ru": "В 2025 году сдано более 5000 новых жилых единиц", "bs": "U 2025 isporučeno je više od 5.000 novih stambenih jedinica"}, sort_order: 3 },
    { text: {"tr": "Alanya, Türkiye'de yabancılara en çok konut satılan 3. şehir", "en": "Alanya ranks 3rd in Turkey for property sales to foreigners", "de": "Alanya ist die 3. Stadt beim Immobilienverkauf an Ausländer", "ru": "Аланья занимает 3-е место по продаже недвижимости иностранцам", "bs": "Alanja je treći grad po prodaji nekretnina strancima"}, sort_order: 4 },
    { text: {"tr": "Vatandaşlık programı ile 10.000+ yabancı yatırımcı Türk vatandaşlığı edindi", "en": "10,000+ foreign investors gained Turkish citizenship through the citizenship program", "de": "Über 10.000 Investoren erhielten die türkische Staatsbürgerschaft", "ru": "Более 10 000 инвесторов получили турецкое гражданство", "bs": "Više od 10.000 investitora steklo je tursko državljanstvo"}, sort_order: 5 }
  ]

  const { error: hlError } = await supabase.from('market_highlights').insert(highlights)
  if (hlError) console.error(`  ✗ market_highlights: ${hlError.message}`)
  else console.log(`  ✓ ${highlights.length} market highlights inserted`)

  // ── 3. PROPERTIES ───────────────────────────────────────────────
  console.log('\n── Inserting properties ──')
  const properties = [
    { name: {"tr": "Deniz Manzaralı Lüks Villa", "en": "Sea View Luxury Villa", "de": "Luxusvilla mit Meerblick", "ru": "Роскошная вилла с видом на море", "bs": "Luksuzna vila s pogledom na more"}, slug: 'deniz-manzarali-luks-villa', location: {"tr": "Kargıcak, Alanya", "en": "Kargicak, Alanya", "de": "Kargıcak, Alanya", "ru": "Каргыджак, Аланья", "bs": "Kargıcak, Alanya"}, price: '€485.000', type: 'villa', type_label: {"tr": "Villa", "en": "Villa", "de": "Villa", "ru": "Вилла", "bs": "Vila"}, beds: 4, sqft: '280 m²', image: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&q=80&fit=crop', featured: true, description: 'Akdeniz\'in büyüleyici manzarasına sahip bu muhteşem villa.', gallery: ['https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&q=80&fit=crop'], amenities: ['Özel Havuz', 'Deniz Manzarası', 'Merkezi Klima', 'Otopark', 'Güvenlik', 'Bahçe'], developer: 'Alanya Premium Yapı', year: '2024', sort_order: 0 },
    { name: {"tr": "Modern Residence Daire", "en": "Modern Residence Apartment", "de": "Moderne Residenz-Wohnung", "ru": "Современная резиденция", "bs": "Moderni stan u rezidenciji"}, slug: 'modern-residence-daire-mahmutlar', location: {"tr": "Mahmutlar, Alanya", "en": "Mahmutlar, Alanya", "de": "Mahmutlar, Alanya", "ru": "Махмутлар, Аланья", "bs": "Mahmutlar, Alanya"}, price: '€89.000', type: 'apartment', type_label: {"tr": "Daire", "en": "Apartment", "de": "Wohnung", "ru": "Квартира", "bs": "Stan"}, beds: 2, sqft: '95 m²', image: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&q=80&fit=crop', featured: true, description: 'Mahmutlar\'ın kalbinde modern residence.', gallery: ['https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&q=80&fit=crop'], amenities: ['Havuz', 'Fitness', 'Sauna', 'Otopark', 'Güvenlik'], developer: 'Mahmutlar İnşaat', year: '2025', sort_order: 1 },
    { name: {"tr": "Premium Penthouse", "en": "Premium Penthouse", "de": "Premium-Penthouse", "ru": "Премиум пентхаус", "bs": "Premium penthaus"}, slug: 'premium-penthouse-oba', location: {"tr": "Oba, Alanya", "en": "Oba, Alanya", "de": "Oba, Alanya", "ru": "Оба, Аланья", "bs": "Oba, Alanya"}, price: '€320.000', type: 'penthouse', type_label: {"tr": "Penthouse", "en": "Penthouse", "de": "Penthouse", "ru": "Пентхаус", "bs": "Penthaus"}, beds: 3, sqft: '210 m²', image: 'https://images.unsplash.com/photo-1600607687644-c7171b42498f?w=800&q=80&fit=crop', featured: true, description: 'Oba\'nın en prestijli adresinde premium penthouse.', gallery: ['https://images.unsplash.com/photo-1600607687644-c7171b42498f?w=800&q=80&fit=crop'], amenities: ['Panoramik Manzara', 'Özel Teras', 'Jakuzi', 'Özel Asansör', 'Akıllı Ev'], developer: 'Oba Gayrimenkul', year: '2024', sort_order: 2 },
    { name: {"tr": "Sahil Villası", "en": "Beachfront Villa", "de": "Strandvilla", "ru": "Вилла на берегу моря", "bs": "Vila na obali"}, slug: 'sahil-villasi-kestel', location: {"tr": "Kestel, Alanya", "en": "Kestel, Alanya", "de": "Kestel, Alanya", "ru": "Кестель, Аланья", "bs": "Kestel, Alanya"}, price: '€650.000', type: 'villa', type_label: {"tr": "Villa", "en": "Villa", "de": "Villa", "ru": "Вилла", "bs": "Vila"}, beds: 5, sqft: '350 m²', image: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80&fit=crop', featured: true, description: 'Kestel sahilinde denize sıfır villa.', gallery: ['https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80&fit=crop'], amenities: ['Denize Sıfır', 'Özel Plaj', 'Infinity Havuz', 'Bahçe', 'BBQ Alanı'], developer: 'Kestel Yapı A.Ş.', year: '2023', sort_order: 3 },
    { name: {"tr": "Aile Dairesi", "en": "Family Apartment", "de": "Familienwohnung", "ru": "Семейная квартира", "bs": "Porodični stan"}, slug: 'aile-dairesi-tosmur', location: {"tr": "Tosmur, Alanya", "en": "Tosmur, Alanya", "de": "Tosmur, Alanya", "ru": "Тосмур, Аланья", "bs": "Tosmur, Alanya"}, price: '€115.000', type: 'apartment', type_label: {"tr": "Daire", "en": "Apartment", "de": "Wohnung", "ru": "Квартира", "bs": "Stan"}, beds: 3, sqft: '120 m²', image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80&fit=crop', featured: true, description: 'Tosmur\'un sakin ortamında aile dairesi.', gallery: ['https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80&fit=crop'], amenities: ['Havuz', 'Çocuk Parkı', 'Otopark', 'Güvenlik', 'Balkon'], developer: 'Tosmur Konutları', year: '2024', sort_order: 4 },
    { name: {"tr": "Havuzlu Residence", "en": "Pool Residence", "de": "Residenz mit Pool", "ru": "Резиденция с бассейном", "bs": "Rezidencija s bazenom"}, slug: 'havuzlu-residence-cikcilli', location: {"tr": "Cikcilli, Alanya", "en": "Cikcilli, Alanya", "de": "Cikcilli, Alanya", "ru": "Джикджилли, Аланья", "bs": "Cikcilli, Alanya"}, price: '€135.000', type: 'apartment', type_label: {"tr": "Daire", "en": "Apartment", "de": "Wohnung", "ru": "Квартира", "bs": "Stan"}, beds: 2, sqft: '110 m²', image: 'https://images.unsplash.com/photo-1574362848149-11496d93a7c7?w=800&q=80&fit=crop', featured: true, description: 'Cikcilli\'de yatırım değeri yüksek residence.', gallery: ['https://images.unsplash.com/photo-1574362848149-11496d93a7c7?w=800&q=80&fit=crop'], amenities: ['Açık Havuz', 'Kapalı Havuz', 'SPA', 'Fitness', 'Sauna'], developer: 'Cikcilli Yapı', year: '2025', sort_order: 5 },
    { name: {"tr": "Doğa Manzaralı Villa", "en": "Nature View Villa", "de": "Villa mit Naturblick", "ru": "Вилла с видом на природу", "bs": "Vila s pogledom na prirodu"}, slug: 'doga-manzarali-villa-avsallar', location: {"tr": "Avsallar, Alanya", "en": "Avsallar, Alanya", "de": "Avsallar, Alanya", "ru": "Авсаллар, Аланья", "bs": "Avsallar, Alanya"}, price: '€380.000', type: 'villa', type_label: {"tr": "Villa", "en": "Villa", "de": "Villa", "ru": "Вилла", "bs": "Vila"}, beds: 4, sqft: '250 m²', image: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&q=80&fit=crop', featured: false, description: 'Avsallar\'ın eşsiz doğası içinde villa.', gallery: ['https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&q=80&fit=crop'], amenities: ['Özel Havuz', 'Büyük Bahçe', 'Dağ Manzarası', 'Otopark'], developer: 'Avsallar İnşaat', year: '2024', sort_order: 6 },
    { name: {"tr": "Stüdyo Daire", "en": "Studio Apartment", "de": "Studio-Wohnung", "ru": "Квартира-студия", "bs": "Garsonjera"}, slug: 'studyo-daire-mahmutlar', location: {"tr": "Mahmutlar, Alanya", "en": "Mahmutlar, Alanya", "de": "Mahmutlar, Alanya", "ru": "Махмутлар, Аланья", "bs": "Mahmutlar, Alanya"}, price: '€65.000', type: 'apartment', type_label: {"tr": "Stüdyo", "en": "Studio", "de": "Studio", "ru": "Студия", "bs": "Studio"}, beds: 1, sqft: '55 m²', image: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80&fit=crop', featured: false, description: 'Mahmutlar\'da yatırımlık stüdyo daire.', gallery: ['https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80&fit=crop'], amenities: ['Eşyalı', 'Havuz', 'Fitness', 'Güvenlik'], developer: 'Mahmutlar Residence', year: '2023', sort_order: 7 },
    { name: {"tr": "Dubleks Penthouse", "en": "Duplex Penthouse", "de": "Duplex-Penthouse", "ru": "Двухуровневый пентхаус", "bs": "Dupleks penthaus"}, slug: 'dubleks-penthouse-oba', location: {"tr": "Oba, Alanya", "en": "Oba, Alanya", "de": "Oba, Alanya", "ru": "Оба, Аланья", "bs": "Oba, Alanya"}, price: '€445.000', type: 'penthouse', type_label: {"tr": "Penthouse", "en": "Penthouse", "de": "Penthouse", "ru": "Пентхаус", "bs": "Penthaus"}, beds: 4, sqft: '280 m²', image: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80&fit=crop', featured: false, description: 'Oba\'da lüks dubleks penthouse.', gallery: ['https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80&fit=crop'], amenities: ['Çift Kat', 'Özel Teras', 'Deniz Manzarası', 'Jakuzi'], developer: 'Oba Lüks Yapı', year: '2025', sort_order: 8 },
    { name: {"tr": "Denize Sıfır Daire", "en": "Beachfront Apartment", "de": "Wohnung am Strand", "ru": "Квартира на берегу моря", "bs": "Stan na plaži"}, slug: 'denize-sifir-daire-kestel', location: {"tr": "Kestel, Alanya", "en": "Kestel, Alanya", "de": "Kestel, Alanya", "ru": "Кестель, Аланья", "bs": "Kestel, Alanya"}, price: '€175.000', type: 'apartment', type_label: {"tr": "Daire", "en": "Apartment", "de": "Wohnung", "ru": "Квартира", "bs": "Stan"}, beds: 2, sqft: '105 m²', image: 'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800&q=80&fit=crop', featured: false, description: 'Kestel sahilinde denize sıfır daire.', gallery: ['https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800&q=80&fit=crop'], amenities: ['Denize Sıfır', 'Özel Plaj', 'Havuz', 'Fitness'], developer: 'Kestel Marina Yapı', year: '2024', sort_order: 9 },
    { name: {"tr": "Müstakil Villa", "en": "Detached Villa", "de": "Freistehende Villa", "ru": "Отдельная вилла", "bs": "Samostalna vila"}, slug: 'mustakil-villa-kargicak', location: {"tr": "Kargıcak, Alanya", "en": "Kargicak, Alanya", "de": "Kargıcak, Alanya", "ru": "Каргыджак, Аланья", "bs": "Kargıcak, Alanya"}, price: '€520.000', type: 'villa', type_label: {"tr": "Villa", "en": "Villa", "de": "Villa", "ru": "Вилла", "bs": "Vila"}, beds: 5, sqft: '320 m²', image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80&fit=crop', featured: false, description: 'Kargıcak\'ta 180° deniz manzaralı müstakil villa.', gallery: ['https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80&fit=crop'], amenities: ['Müstakil', 'Özel Havuz', 'Deniz Manzarası', 'Garaj'], developer: 'Kargıcak Villa Park', year: '2023', sort_order: 10 },
    { name: {"tr": "Lüks Residence Daire", "en": "Luxury Residence Apartment", "de": "Luxus-Residenz-Wohnung", "ru": "Роскошная резиденция", "bs": "Luksuzni stan u rezidenciji"}, slug: 'luks-residence-konakli', location: {"tr": "Konaklı, Alanya", "en": "Konakli, Alanya", "de": "Konaklı, Alanya", "ru": "Конаклы, Аланья", "bs": "Konaklı, Alanya"}, price: '€155.000', type: 'apartment', type_label: {"tr": "Daire", "en": "Apartment", "de": "Wohnung", "ru": "Квартира", "bs": "Stan"}, beds: 3, sqft: '130 m²', image: 'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800&q=80&fit=crop', featured: false, description: 'Konaklı\'nın merkezinde lüks residence.', gallery: ['https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800&q=80&fit=crop'], amenities: ['Havuz', 'Fitness', 'Sauna', 'Türk Hamamı', 'Otopark'], developer: 'Konaklı Yapı', year: '2024', sort_order: 11 },
    { name: {"tr": "Bahçeli Villa", "en": "Garden Villa", "de": "Villa mit Garten", "ru": "Вилла с садом", "bs": "Vila s vrtom"}, slug: 'bahceli-villa-tosmur', location: {"tr": "Tosmur, Alanya", "en": "Tosmur, Alanya", "de": "Tosmur, Alanya", "ru": "Тосмур, Аланья", "bs": "Tosmur, Alanya"}, price: '€290.000', type: 'villa', type_label: {"tr": "Villa", "en": "Villa", "de": "Villa", "ru": "Вилла", "bs": "Vila"}, beds: 3, sqft: '200 m²', image: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800&q=80&fit=crop', featured: false, description: 'Tosmur\'da geniş bahçeli villa.', gallery: ['https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800&q=80&fit=crop'], amenities: ['Özel Havuz', 'Geniş Bahçe', 'Otopark', 'BBQ', 'Teras'], developer: 'Tosmur Evleri', year: '2024', sort_order: 12 },
    { name: {"tr": "Smart Home Daire", "en": "Smart Home Apartment", "de": "Smart-Home-Wohnung", "ru": "Умная квартира", "bs": "Pametni stan"}, slug: 'smart-home-daire-mahmutlar', location: {"tr": "Mahmutlar, Alanya", "en": "Mahmutlar, Alanya", "de": "Mahmutlar, Alanya", "ru": "Махмутлар, Аланья", "bs": "Mahmutlar, Alanya"}, price: '€98.000', type: 'apartment', type_label: {"tr": "Daire", "en": "Apartment", "de": "Wohnung", "ru": "Квартира", "bs": "Stan"}, beds: 2, sqft: '85 m²', image: 'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=800&q=80&fit=crop', featured: false, description: 'Mahmutlar\'da akıllı ev sistemli daire.', gallery: ['https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=800&q=80&fit=crop'], amenities: ['Akıllı Ev', 'Havuz', 'Fitness', 'Otopark', 'Güvenlik'], developer: 'Smart Living', year: '2025', sort_order: 13 },
    { name: {"tr": "Panoramik Penthouse", "en": "Panoramic Penthouse", "de": "Panorama-Penthouse", "ru": "Панорамный пентхаус", "bs": "Panoramski penthaus"}, slug: 'panoramik-penthouse-cikcilli', location: {"tr": "Cikcilli, Alanya", "en": "Cikcilli, Alanya", "de": "Cikcilli, Alanya", "ru": "Джикджилли, Аланья", "bs": "Cikcilli, Alanya"}, price: '€275.000', type: 'penthouse', type_label: {"tr": "Penthouse", "en": "Penthouse", "de": "Penthouse", "ru": "Пентхаус", "bs": "Penthaus"}, beds: 3, sqft: '185 m²', image: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&q=80&fit=crop', featured: false, description: 'Cikcilli\'de panoramik manzaralı penthouse.', gallery: ['https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&q=80&fit=crop'], amenities: ['Panoramik Manzara', 'Geniş Teras', 'Açık Mutfak', 'Havuz'], developer: 'Cikcilli Premium', year: '2024', sort_order: 14 },
    { name: {"tr": "Tatil Villası", "en": "Holiday Villa", "de": "Ferienvilla", "ru": "Вилла для отдыха", "bs": "Vila za odmor"}, slug: 'tatil-villasi-avsallar', location: {"tr": "Avsallar, Alanya", "en": "Avsallar, Alanya", "de": "Avsallar, Alanya", "ru": "Авсаллар, Аланья", "bs": "Avsallar, Alanya"}, price: '€340.000', type: 'villa', type_label: {"tr": "Villa", "en": "Villa", "de": "Villa", "ru": "Вилла", "bs": "Vila"}, beds: 3, sqft: '220 m²', image: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800&q=80&fit=crop', featured: false, description: 'Avsallar\'da tatil ve yatırım villası.', gallery: ['https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800&q=80&fit=crop'], amenities: ['Özel Havuz', 'Bahçe', 'BBQ', 'Klima', 'Eşyalı'], developer: 'Avsallar Holiday Homes', year: '2024', sort_order: 15 },
    { name: {"tr": "Yatırımlık Daire", "en": "Investment Apartment", "de": "Investment-Wohnung", "ru": "Инвестиционная квартира", "bs": "Investicioni stan"}, slug: 'yatirimlik-daire-mahmutlar', location: {"tr": "Mahmutlar, Alanya", "en": "Mahmutlar, Alanya", "de": "Mahmutlar, Alanya", "ru": "Махмутлар, Аланья", "bs": "Mahmutlar, Alanya"}, price: '€72.000', type: 'apartment', type_label: {"tr": "Daire", "en": "Apartment", "de": "Wohnung", "ru": "Квартира", "bs": "Stan"}, beds: 1, sqft: '65 m²', image: 'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800&q=80&fit=crop', featured: false, description: 'Mahmutlar\'da uygun fiyatlı yatırımlık daire.', gallery: ['https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800&q=80&fit=crop'], amenities: ['Havuz', 'Güvenlik', 'Otopark', 'Balkon'], developer: 'Mahmutlar Evleri', year: '2023', sort_order: 16 },
    { name: {"tr": "Teras Daire", "en": "Terrace Apartment", "de": "Terrassenwohnung", "ru": "Квартира с террасой", "bs": "Stan s terasom"}, slug: 'teras-daire-oba', location: {"tr": "Oba, Alanya", "en": "Oba, Alanya", "de": "Oba, Alanya", "ru": "Оба, Аланья", "bs": "Oba, Alanya"}, price: '€145.000', type: 'apartment', type_label: {"tr": "Daire", "en": "Apartment", "de": "Wohnung", "ru": "Квартира", "bs": "Stan"}, beds: 2, sqft: '115 m²', image: 'https://images.unsplash.com/photo-1600210492493-0946911123ea?w=800&q=80&fit=crop', featured: false, description: 'Oba\'da geniş teraslı modern daire.', gallery: ['https://images.unsplash.com/photo-1600210492493-0946911123ea?w=800&q=80&fit=crop'], amenities: ['Geniş Teras', 'Havuz', 'Merkezi Konum', 'Otopark'], developer: 'Oba Konut', year: '2025', sort_order: 17 },
    { name: {"tr": "Lüks Müstakil Villa", "en": "Luxury Detached Villa", "de": "Luxus-Einzelvilla", "ru": "Роскошная отдельная вилла", "bs": "Luksuzna samostalna vila"}, slug: 'luks-mustakil-villa-kargicak', location: {"tr": "Kargıcak, Alanya", "en": "Kargicak, Alanya", "de": "Kargıcak, Alanya", "ru": "Каргыджак, Аланья", "bs": "Kargıcak, Alanya"}, price: '€780.000', type: 'villa', type_label: {"tr": "Villa", "en": "Villa", "de": "Villa", "ru": "Вилла", "bs": "Vila"}, beds: 6, sqft: '420 m²', image: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80&fit=crop', featured: false, description: 'Kargıcak\'ta ultra lüks villa.', gallery: ['https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80&fit=crop'], amenities: ['Infinity Havuz', 'Sinema Odası', 'Şarap Mahzeni', 'Akıllı Ev', 'Asansör'], developer: 'Kargıcak Premium', year: '2024', sort_order: 18 },
    { name: {"tr": "Rezidans Daire", "en": "Residence Apartment", "de": "Residenz-Wohnung", "ru": "Квартира в резиденции", "bs": "Stan u rezidenciji"}, slug: 'rezidans-daire-konakli', location: {"tr": "Konaklı, Alanya", "en": "Konakli, Alanya", "de": "Konaklı, Alanya", "ru": "Конаклы, Аланья", "bs": "Konaklı, Alanya"}, price: '€108.000', type: 'apartment', type_label: {"tr": "Daire", "en": "Apartment", "de": "Wohnung", "ru": "Квартира", "bs": "Stan"}, beds: 2, sqft: '90 m²', image: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80&fit=crop', featured: false, description: 'Konaklı\'da modern rezidans daire.', gallery: ['https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80&fit=crop'], amenities: ['Havuz', 'Fitness', 'Otopark', 'Güvenlik', 'Çocuk Parkı'], developer: 'Konaklı Residence', year: '2025', sort_order: 19 }
  ]

  const { error: propError } = await supabase.from('properties').insert(properties)
  if (propError) console.error(`  ✗ properties: ${propError.message}`)
  else console.log(`  ✓ ${properties.length} properties inserted`)

  // ── 4. AREAS ────────────────────────────────────────────────────
  console.log('\n── Inserting areas ──')
  const areas = [
    { key: 'mahmutlar', slug: 'mahmutlar', name: {"tr": "Mahmutlar", "en": "Mahmutlar", "de": "Mahmutlar", "ru": "Махмутлар", "bs": "Mahmutlar"}, description: {"tr": "Alanya'nın en popüler yatırım bölgesi.", "en": "Alanya's most popular investment area.", "de": "Alanyas beliebtestes Investitionsgebiet.", "ru": "Самый популярный инвестиционный район Аланьи.", "bs": "Najpopularnija investiciona zona Alanje."}, description_long: {"tr": "Mahmutlar, Alanya'nın doğusunda en büyük ve en hızlı gelişen bölgelerden biridir.", "en": "Mahmutlar is one of the largest and fastest-growing districts east of Alanya.", "de": "Mahmutlar ist einer der größten Stadtteile östlich von Alanya.", "ru": "Махмутлар — один из крупнейших районов к востоку от Аланьи.", "bs": "Mahmutlar je jedna od najvećih četvrti istočno od Alanje."}, avg_price: '€65.000 - €180.000', roi: '%8-12', image: 'https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?w=800&q=80&fit=crop', highlights: ['Denize 300m mesafe', 'Zengin altyapı', 'Yabancı yatırımcı dostu', 'Uygun fiyat/performans', 'Yıl boyu yaşanabilir', 'Yüksek kira getirisi'], featured: true, sort_order: 0 },
    { key: 'oba', slug: 'oba', name: {"tr": "Oba", "en": "Oba", "de": "Oba", "ru": "Оба", "bs": "Oba"}, description: {"tr": "Alanya'nın modern şehir merkezi. Premium projeler.", "en": "Alanya's modern city center. Premium projects.", "de": "Alanyas modernes Stadtzentrum.", "ru": "Современный центр Аланьи.", "bs": "Moderni centar Alanje."}, description_long: {"tr": "Oba, Alanya'nın en merkezi ve prestijli bölgesidir.", "en": "Oba is Alanya's most central and prestigious district.", "de": "Oba ist der zentralste Stadtteil von Alanya.", "ru": "Оба — самый центральный район Аланьи.", "bs": "Oba je najcentralnija četvrt Alanje."}, avg_price: '€120.000 - €450.000', roi: '%6-10', image: 'https://images.unsplash.com/photo-1449844908441-8829872d2607?w=800&q=80&fit=crop', highlights: ['Şehir merkezi konumu', 'Premium projeler', 'Hastane ve okul yakınlığı', 'Alışveriş merkezleri', 'Restoran ve kafeler', 'Modern altyapı'], featured: true, sort_order: 1 },
    { key: 'kestel', slug: 'kestel', name: {"tr": "Kestel", "en": "Kestel", "de": "Kestel", "ru": "Кестель", "bs": "Kestel"}, description: {"tr": "Denize sıfır konumu ve doğal güzelliğiyle sahil bölgesi.", "en": "Coastal district with beachfront location.", "de": "Küstengebiet mit Strandlage.", "ru": "Прибрежный район.", "bs": "Obalna četvrt."}, description_long: {"tr": "Kestel, Alanya merkezinin batısında sakin bir sahil bölgesidir.", "en": "Kestel is a quiet coastal district west of Alanya center.", "de": "Kestel ist ein ruhiger Küstenbezirk.", "ru": "Кестель — тихий прибрежный район.", "bs": "Kestel je mirna obalna četvrt."}, avg_price: '€100.000 - €650.000', roi: '%7-11', image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80&fit=crop', highlights: ['Denize sıfır projeler', 'Kleopatra Plajı yakınlığı', 'Doğal güzellik', 'Sakin ortam', 'Su sporları', 'Kalıcı konut'], featured: true, sort_order: 2 },
    { key: 'kargicak', slug: 'kargicak', name: {"tr": "Kargıcak", "en": "Kargicak", "de": "Kargıcak", "ru": "Каргыджак", "bs": "Kargıcak"}, description: {"tr": "Lüks villaların adresi. Eşsiz deniz manzarası.", "en": "Home of luxury villas. Unique sea views.", "de": "Heimat der Luxusvillen.", "ru": "Дом роскошных вилл.", "bs": "Dom luksuznih vila."}, description_long: {"tr": "Kargıcak, lüks villa projeleriyle tanınan prestijli bir bölgedir.", "en": "Kargicak is a prestigious district known for luxury villas.", "de": "Kargıcak ist ein prestigeträchtiger Stadtteil.", "ru": "Каргыджак — престижный район.", "bs": "Kargıcak je prestižna četvrt."}, avg_price: '€350.000 - €800.000', roi: '%5-9', image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80&fit=crop', highlights: ['Lüks villa projeleri', 'Eşsiz deniz manzarası', 'Özel yaşam alanları', 'Doğa ile iç içe', 'Yüksek yatırım değeri', 'Premium konfor'], featured: true, sort_order: 3 },
    { key: 'tosmur', slug: 'tosmur', name: {"tr": "Tosmur", "en": "Tosmur", "de": "Tosmur", "ru": "Тосмур", "bs": "Tosmur"}, description: {"tr": "Aileler için ideal, sakin yaşam bölgesi.", "en": "Ideal for families, peaceful area.", "de": "Ideal für Familien.", "ru": "Идеально для семей.", "bs": "Idealna za porodice."}, description_long: {"tr": "Tosmur, hem şehir hayatına yakın hem de sakin bir yaşam sunar.", "en": "Tosmur offers both proximity to city life and quiet living.", "de": "Tosmur bietet Stadtnähe und ruhiges Wohnen.", "ru": "Тосмур предлагает близость к городу и тихое проживание.", "bs": "Tosmur nudi blizinu gradu i mirno stanovanje."}, avg_price: '€90.000 - €300.000', roi: '%7-10', image: 'https://images.unsplash.com/photo-1518780664697-55e3ad937233?w=800&q=80&fit=crop', highlights: ['Aile dostu ortam', 'Dim Çayı yakınlığı', 'Yeşil alanlar', 'Merkeze yakın', 'Uygun fiyatlar', 'Sakin çevre'], featured: false, sort_order: 4 },
    { key: 'cikcilli', slug: 'cikcilli', name: {"tr": "Cikcilli", "en": "Cikcilli", "de": "Cikcilli", "ru": "Джикджилли", "bs": "Cikcilli"}, description: {"tr": "Hızla gelişen, yatırım potansiyeli yüksek bölge.", "en": "Rapidly developing with high investment potential.", "de": "Schnell wachsend mit hohem Investitionspotenzial.", "ru": "Быстро развивающийся район.", "bs": "Brzorastuća zona."}, description_long: {"tr": "Cikcilli, yeni nesil residence projelerine ev sahipliği yapan modern bölgedir.", "en": "Cikcilli hosts new-generation residence projects.", "de": "Cikcilli beherbergt neue Residenzprojekte.", "ru": "Джикджилли принимает проекты нового поколения.", "bs": "Cikcilli ugošćuje projekte nove generacije."}, avg_price: '€80.000 - €280.000', roi: '%9-14', image: 'https://images.unsplash.com/photo-1460317442991-0ec209397118?w=800&q=80&fit=crop', highlights: ['Hızlı değer artışı', 'Yeni nesil projeler', 'Stratejik konum', 'Uygun giriş fiyatları', 'Modern altyapı', 'Yüksek ROI'], featured: false, sort_order: 5 },
    { key: 'avsallar', slug: 'avsallar', name: {"tr": "Avsallar", "en": "Avsallar", "de": "Avsallar", "ru": "Авсаллар", "bs": "Avsallar"}, description: {"tr": "Doğa, deniz ve huzurun buluştuğu tatil cenneti.", "en": "Holiday paradise with nature, sea and peace.", "de": "Urlaubsparadies.", "ru": "Райский уголок.", "bs": "Raj za odmor."}, description_long: {"tr": "Avsallar, İncekum Plajı ile ünlü doğal tatil bölgesidir.", "en": "Avsallar is famous for Incekum Beach.", "de": "Avsallar ist berühmt für den Incekum-Strand.", "ru": "Авсаллар известен пляжем Инджекум.", "bs": "Avsallar je poznat po plaži Incekum."}, avg_price: '€70.000 - €350.000', roi: '%8-12', image: 'https://images.unsplash.com/photo-1506929562872-bb421503ef21?w=800&q=80&fit=crop', highlights: ['İncekum Plajı', 'Doğal güzellik', 'Toros Dağları manzarası', 'Tatil ve emeklilik', 'Yüksek kira getirisi', 'Uygun fiyatlar'], featured: false, sort_order: 6 },
    { key: 'konakli', slug: 'konakli', name: {"tr": "Konaklı", "en": "Konakli", "de": "Konaklı", "ru": "Конаклы", "bs": "Konaklı"}, description: {"tr": "Tarihi doku ve modern yaşamın harmonisi.", "en": "Harmony of history and modern living.", "de": "Harmonie von Geschichte und modernem Leben.", "ru": "Гармония истории и современной жизни.", "bs": "Harmonija historije i modernog života."}, description_long: {"tr": "Konaklı, tarihi ve kültürel zenginliğe sahip bir bölgedir.", "en": "Konakli has rich historical and cultural heritage.", "de": "Konaklı hat reiches historisches Erbe.", "ru": "Конаклы имеет богатое историческое наследие.", "bs": "Konaklı ima bogato historijsko naslijeđe."}, avg_price: '€75.000 - €200.000', roi: '%7-11', image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80&fit=crop', highlights: ['Tarihi kalıntılar', 'Yerel pazar', 'Geleneksel atmosfer', 'Uygun fiyatlar', 'Turizm potansiyeli', 'Modern projeler'], featured: false, sort_order: 7 }
  ]

  const { error: areaError } = await supabase.from('areas').insert(areas)
  if (areaError) console.error(`  ✗ areas: ${areaError.message}`)
  else console.log(`  ✓ ${areas.length} areas inserted`)

  // ── 5. GOLDEN VISA ──────────────────────────────────────────────
  console.log('\n── Inserting golden visa content ──')
  const goldenVisa = [
    { section: 'benefit', key: 'residency', title: 'Tam Vatandaşlık Hakkı', description: 'Kendiniz ve aileniz için kalıcı Türk vatandaşlığı.', sort_order: 0 },
    { section: 'benefit', key: 'family', title: 'Aile Dahil Vatandaşlık', description: 'Eşiniz ve çocuklarınız da vatandaşlık hakkı kazanır.', sort_order: 1 },
    { section: 'benefit', key: 'business', title: 'İş Kurma Özgürlüğü', description: 'Türkiye genelinde şirket kurun ve yönetin.', sort_order: 2 },
    { section: 'benefit', key: 'travel', title: 'Vizesiz Seyahat', description: '110+ ülkeye vizesiz seyahat.', sort_order: 3 },
    { section: 'benefit', key: 'tax', title: 'Avantajlı Vergi Sistemi', description: 'Rekabetçi vergi oranları ve teşvikler.', sort_order: 4 },
    { section: 'benefit', key: 'healthcare', title: 'Kaliteli Yaşam Standartları', description: 'Dünya standartlarında sağlık ve eğitim hizmetleri.', sort_order: 5 },
    { section: 'eligibility', key: 'eligibility_1', title: null, description: 'Minimum 400.000 USD gayrimenkul satın alın.', sort_order: 0 },
    { section: 'eligibility', key: 'eligibility_2', title: null, description: 'Mülk en az 3 yıl satılamaz.', sort_order: 1 },
    { section: 'eligibility', key: 'eligibility_3', title: null, description: 'Konut veya ticari mülk uygundur.', sort_order: 2 },
    { section: 'eligibility', key: 'eligibility_4', title: null, description: 'Birden fazla mülk birleştirilebilir.', sort_order: 3 },
    { section: 'eligibility', key: 'eligibility_5', title: null, description: 'Temiz adli sicil ve sağlık sigortası gereklidir.', sort_order: 4 },
    { section: 'eligibility', key: 'eligibility_6', title: null, description: 'Resmi değerleme raporu zorunludur.', sort_order: 5 },
    { section: 'process_step', key: 'step_1', title: 'Mülk Seçimi', description: 'Danışmanlarımızla mülk seçin.', sort_order: 0 },
    { section: 'process_step', key: 'step_2', title: 'Satın Alma ve Tescil', description: 'Mülkü satın alın, tapu tescili yapılır.', sort_order: 1 },
    { section: 'process_step', key: 'step_3', title: 'Belge Hazırlığı', description: 'Gerekli belgeleri toplayın.', sort_order: 2 },
    { section: 'process_step', key: 'step_4', title: 'Vatandaşlık Onayı', description: '3-6 ay içinde vatandaşlığınızı edinin.', sort_order: 3 }
  ]

  const { error: gvError } = await supabase.from('golden_visa_content').insert(goldenVisa)
  if (gvError) console.error(`  ✗ golden_visa_content: ${gvError.message}`)
  else console.log(`  ✓ ${goldenVisa.length} entries inserted`)

  // ── 6. BLOG POSTS ───────────────────────────────────────────────
  console.log('\n── Inserting blog posts ──')
  const blogPosts = [
    { slug: 'alanyada-gayrimenkul-yatiriminin-5-avantaji', title: {"tr": "Alanya'da Gayrimenkul Yatırımının 5 Avantajı", "en": "5 Advantages of Real Estate Investment in Alanya"}, excerpt: {"tr": "Alanya, Türkiye'nin en cazip yatırım destinasyonu.", "en": "Alanya is Turkey's most attractive investment destination."}, content: {"tr": "<h2>Uygun Fiyatlar</h2><p>Akdeniz'de en uygun fiyatlı gayrimenkul.</p>", "en": "<h2>Affordable Prices</h2><p>Most affordable Mediterranean real estate.</p>"}, date: '2025-01-15', published_at: '2025-01-15T10:00:00Z', category: {"tr": "Yatırım", "en": "Investment"}, category_color: 'bg-blue-100 text-blue-800', image: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&q=80&fit=crop', published: true, sort_order: 0 },
    { slug: '2025te-alanya-emlak-piyasasi-trendleri', title: {"tr": "2025'te Alanya Emlak Piyasası Trendleri", "en": "Alanya Real Estate Trends 2025"}, excerpt: {"tr": "Alanya piyasası büyümeye devam ediyor.", "en": "Alanya market continues growing."}, content: {"tr": "<h2>Büyüme</h2><p>%15 büyüme.</p>", "en": "<h2>Growth</h2><p>15% growth.</p>"}, date: '2025-02-01', published_at: '2025-02-01T10:00:00Z', category: {"tr": "Piyasa Analizi", "en": "Market Analysis"}, category_color: 'bg-emerald-100 text-emerald-800', image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&q=80&fit=crop', published: true, sort_order: 1 },
    { slug: 'yabancilar-icin-mulk-satin-alma-rehberi', title: {"tr": "Yabancılar İçin Mülk Satın Alma Rehberi", "en": "Property Buying Guide for Foreigners"}, excerpt: {"tr": "Alanya'da mülk satın alma A'dan Z'ye.", "en": "Complete property buying guide."}, content: {"tr": "<h2>Yasal Süreç</h2><p>Yabancılar tapu alabilir.</p>", "en": "<h2>Legal Process</h2><p>Foreigners can buy property.</p>"}, date: '2025-01-20', published_at: '2025-01-20T10:00:00Z', category: {"tr": "Rehber", "en": "Guide"}, category_color: 'bg-violet-100 text-violet-800', image: 'https://images.unsplash.com/photo-1554469384-e58fac16e23a?w=800&q=80&fit=crop', published: true, sort_order: 2 },
    { slug: 'alanyanin-en-iyi-yatirim-bolgeleri', title: {"tr": "Alanya'nın En İyi Yatırım Bölgeleri", "en": "Best Investment Areas in Alanya"}, excerpt: {"tr": "Her bölgenin avantaj ve potansiyelini karşılaştırdık.", "en": "We compared each district's advantages."}, content: {"tr": "<h2>Mahmutlar</h2><p>En iyi fiyat/performans.</p>", "en": "<h2>Mahmutlar</h2><p>Best value.</p>"}, date: '2025-02-10', published_at: '2025-02-10T10:00:00Z', category: {"tr": "Yatırım", "en": "Investment"}, category_color: 'bg-blue-100 text-blue-800', image: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80&fit=crop', published: true, sort_order: 3 },
    { slug: 'turkiyede-gayrimenkul-ile-vatandaslik', title: {"tr": "Türkiye'de Gayrimenkul ile Vatandaşlık", "en": "Turkish Citizenship Through Real Estate"}, excerpt: {"tr": "400.000 USD üzeri alımla vatandaşlık.", "en": "Citizenship through $400K+ property."}, content: {"tr": "<h2>Program</h2><p>2018'den beri vatandaşlık imkanı.</p>", "en": "<h2>Program</h2><p>Citizenship since 2018.</p>"}, date: '2025-01-25', published_at: '2025-01-25T10:00:00Z', category: {"tr": "Vatandaşlık", "en": "Citizenship"}, category_color: 'bg-amber-100 text-amber-800', image: 'https://images.unsplash.com/photo-1512632578888-169bbbc64f33?w=800&q=80&fit=crop', published: true, sort_order: 4 },
    { slug: 'alanyada-kiralik-mulk-yatirimi', title: {"tr": "Alanya'da Kiralık Mülk Yatırımı", "en": "Rental Property Investment in Alanya"}, excerpt: {"tr": "Pasif gelir elde etmenin yolları.", "en": "Ways to earn passive income."}, content: {"tr": "<h2>Kısa Dönem</h2><p>Turizm sezonu kiralaması.</p>", "en": "<h2>Short-Term</h2><p>Tourism season rentals.</p>"}, date: '2025-02-15', published_at: '2025-02-15T10:00:00Z', category: {"tr": "Kiralama", "en": "Rental"}, category_color: 'bg-rose-100 text-rose-800', image: 'https://images.unsplash.com/photo-1460317442991-0ec209397118?w=800&q=80&fit=crop', published: true, sort_order: 5 }
  ]

  const { error: blogError } = await supabase.from('blog_posts').insert(blogPosts)
  if (blogError) console.error(`  ✗ blog_posts: ${blogError.message}`)
  else console.log(`  ✓ ${blogPosts.length} blog posts inserted`)

  // ── 7. OFFICE ───────────────────────────────────────────────────
  console.log('\n── Adding Alanya office ──')
  const { error: officeError } = await supabase.from('offices').insert({
    city: 'Alanya',
    address: 'Oba Mah., Alanya, Antalya, Türkiye',
    phone: '+90 242 XXX XXXX',
    image: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&q=80&fit=crop',
    lat: 36.5432,
    lng: 31.9993,
    sort_order: 0
  })
  if (officeError) {
    if (officeError.message.includes('duplicate') || officeError.message.includes('unique')) {
      console.log('  ✓ Alanya office already exists')
    } else {
      console.error(`  ✗ offices: ${officeError.message}`)
    }
  } else {
    console.log('  ✓ Alanya office added')
  }

  console.log('\n════════════════════════════════════════════')
  console.log('  TAMAMLANDI! Tüm veriler Alanya ile güncellendi.')
  console.log('════════════════════════════════════════════')

  process.exit(0)
}

populate().catch(err => {
  console.error('Fatal error:', err)
  process.exit(1)
})
